/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author wiki
 */
import Model.User;
import java.util.ArrayList;
import Controler.UserControler;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class GestionUsers extends javax.swing.JFrame {

    /**
     * Creates new form GestionUsers
     */
    public GestionUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnvoir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableusers = new javax.swing.JTable();
        btnSupprimer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnvoir.setBackground(new java.awt.Color(204, 204, 204));
        btnvoir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnvoir.setText("voir la  Liste des utilisateurs");
        btnvoir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnvoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoirActionPerformed(evt);
            }
        });
        getContentPane().add(btnvoir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 31, 360, 40));

        jTableusers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Firstname", "Lastname", "Login", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableusers);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 350));

        btnSupprimer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSupprimer.setForeground(new java.awt.Color(255, 0, 0));
        btnSupprimer.setText("supprimer");
        btnSupprimer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(btnSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 140, 50));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Page precedente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        btnAjouter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAjouter.setForeground(new java.awt.Color(0, 153, 0));
        btnAjouter.setText("Ajouter");
        btnAjouter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 140, 40));

        btnModifier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModifier.setText("Modifier");
        btnModifier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });
        getContentPane().add(btnModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoirActionPerformed
        // TODO add your handling code here:
         UserControler uc = new UserControler();
         
        ArrayList<User> alu  = new ArrayList<User>();
        alu = (ArrayList<User>) uc.getAll();
 
        
        DefaultTableModel model = new DefaultTableModel() ;
        jTableusers.setModel(model) ; 
        model.addColumn("Id");
        model.addColumn("FirstName");
        model.addColumn("LastName");
        model.addColumn("Login"); 
        model.addColumn("Password");
        
        for(User u : alu){
            model.addRow( new Object[] 
            {   u.getId(),
                u.getFirstname(), 
                u.getLastname(),                            
                u.getLogin(),                        
                u.getPwd()
            });
        }  
        jTableusers.setModel(model);
    }//GEN-LAST:event_btnvoirActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
       UserControler uc = new UserControler();
         
        ArrayList<User> alu  = new ArrayList<User>();
        alu = (ArrayList<User>) uc.getAll();
 
        
        DefaultTableModel model = new DefaultTableModel() ;
        jTableusers.setModel(model) ; 
        model.addColumn("Id");
        model.addColumn("FirstName");
        model.addColumn("LastName");
        model.addColumn("Login"); 
        model.addColumn("Password");
        
        for(User u : alu){
            model.addRow( new Object[] 
            {   u.getId(),
                u.getFirstname(), 
                u.getLastname(),                            
                u.getLogin(),                        
                u.getPwd()
            });
        }  
        
        jTableusers.setModel(model); 
     int selectedRow = jTableusers.getSelectedRow();
   
        // Récupérez les données de la ligne sélectionnée
        int id = (int) jTableusers.getValueAt(selectedRow, 0);
        String nomAeroport = (String) jTableusers.getValueAt(selectedRow, 1);
       String pays = (String) jTableusers.getValueAt(selectedRow, 2); 
       
        
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed

    this.setVisible(false);
        new Register().setVisible(true);
   
   
    
        
    }//GEN-LAST:event_btnAjouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnvoir;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableusers;
    // End of variables declaration//GEN-END:variables
}
