
import Controler.AeroportControler;
import Model.Aeroport;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author wiki
 */
public class GestionAeroport extends javax.swing.JFrame {

    /**
     * Creates new form GestionAeroport
     */
    public GestionAeroport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnvoir = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAeroport = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnvoir.setBackground(new java.awt.Color(204, 204, 204));
        btnvoir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnvoir.setText("Gestion des utilisateurs");
        btnvoir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnvoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoirActionPerformed(evt);
            }
        });
        getContentPane().add(btnvoir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 420, 40));

        btnSupprimer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSupprimer.setForeground(new java.awt.Color(255, 0, 0));
        btnSupprimer.setText("supprimer");
        btnSupprimer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(btnSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 140, 50));

        btnAjouter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAjouter.setForeground(new java.awt.Color(0, 153, 0));
        btnAjouter.setText("Ajouter");
        btnAjouter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 140, 40));

        btnModifier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModifier.setText("Modifier");
        btnModifier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });
        getContentPane().add(btnModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 140, 40));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Page precedente");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jTableAeroport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NomAeroport", "Pays"
            }
        ));
        jTableAeroport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAeroportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAeroport);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 510, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoirActionPerformed

        AeroportControler uc = new AeroportControler();
        ArrayList<Aeroport> alu = new ArrayList<Aeroport>();
        alu = (ArrayList<Aeroport>) uc.getAll();

        DefaultTableModel model = new DefaultTableModel();
        jTableAeroport.setModel(model);
         model.addColumn("Id");
        model.addColumn("NomAeroport");
        model.addColumn("Pays");
        

        for (Aeroport u : alu) {
            model.addRow(new Object[]{u.getId(), u.getNomaeroport(), u.getPays()});
        }
        jTableAeroport.setModel(model);
    }//GEN-LAST:event_btnvoirActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
        AeroportControler uc = new AeroportControler();
        ArrayList<Aeroport> alu = new ArrayList<Aeroport>();
        alu = (ArrayList<Aeroport>) uc.getAll();

        int selectedRow = jTableAeroport.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel tableModel = (DefaultTableModel) jTableAeroport.getModel();
            tableModel.removeRow(selectedRow);
            Aeroport selectedUser = alu.get(selectedRow);
            System.out.println(selectedUser.getId());
            uc.delete(selectedUser);

            System.out.println(selectedRow);
            JOptionPane.showMessageDialog(this, "User supprimé avec succes", "Succés", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez selectionner une ligne");
        }

    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed

        this.setVisible(false);
        new AjoutAeroport().setVisible(true);

    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed

    }//GEN-LAST:event_btnModifierActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Admin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableAeroportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAeroportMouseClicked
        int selectedRow = jTableAeroport.getSelectedRow();
        if (selectedRow != -1) {
            // Récupérez les données de la ligne sélectionnée
            int id = (int) jTableAeroport.getValueAt(selectedRow, 0);
            String nomAeroport = (String) jTableAeroport.getValueAt(selectedRow, 1);
            String pays = (String) jTableAeroport.getValueAt(selectedRow, 2);

            // Utilisez les valeurs récupérées dans vos conditions
            if ("Aéroport international de Monastir Habib-Bourguiba".equals(nomAeroport)) {
                // Ouvrez la nouvelle fenêtre en passant les données
                this.setVisible(false);
                new VolM().setVisible(true);
            }else if ("Aéroport international de Tunis-Carthage".equals(nomAeroport)) {
                // Ouvrez la nouvelle fenêtre en passant les données
                this.setVisible(false);
                new VolT().setVisible(true);
            }
            else if ("Aéroport international de Djerba-Zarzis".equals(nomAeroport)) {
                this.setVisible(false);
                new VolDJ().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTableAeroportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAeroport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAeroport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAeroport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAeroport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAeroport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnvoir;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAeroport;
    // End of variables declaration//GEN-END:variables

public class Home extends javax.swing.JFrame {

    private ArrayList<Aeroport> alu = new ArrayList<Aeroport>();
    private AeroportControler uc = new AeroportControler();

    public Home() {
        initComponents();

        alu = (ArrayList<Aeroport>) uc.getAll();

        DefaultTableModel model = new DefaultTableModel();
        jTableAeroport.setModel(model);
        model.addColumn("Id");
        model.addColumn("NomAeroport");
        model.addColumn("Pays");
        

        for (Aeroport u : alu) {
            model.addRow(new Object[]{u.getId(), u.getNomaeroport(), u.getPays()});
        }
        jTableAeroport.setModel(model);
    }

    private void initComponents() {
        // ... Votre code d'initialisation
    }
}
}
